kind: Service
apiVersion: v1
metadata:
  name: myspace-service
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myspace-deployment
  labels:
    app: myspace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myspace
  template:
    metadata:
      labels:
        app: myspace
    spec:
      containers:
      - name: myspace
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
